### PR TITLE
doc: updated readme.md for setup and run on local machine

### PR DESCRIPTION
**Pull request by sahsisunny**
## Description

- Updated [README.md](https://github.com/Real-Dev-Squad/tiny-site-frontend/blob/14bb4fa45e6bad2dc3ef6e606165df784a90f300/README.md)

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [x] Yes
-   [ ] No

_Indicate whether the changes have been tested in the staging environment._

**Under Feature Flag**

-   [x] Yes
-   [ ] No

_Specify if the changes are currently under a feature flag._

**Database Changes**

-   [ ] Yes
-   [x] No

_Indicate whether the changes include modifications to the database._

N/A

Attach any relevant screenshots, such as test coverage reports, before and after images, or other visual aids.

## Test Coverage

N/A
## Additional Notes

N/A

### CODE REVIEW

**Review by satyam73 — COMMENTED** [review]
- Project title and description
- Table of contents
- Tech Stack
- Setup
    - Prerequisite
    - Setup Instructions
- Usage

Also for the prerequisite provide resources. Make sure to add version of the tech stack too.

**Comment by sahsisunny** [comment]
> * Project title and description
> * Table of contents
> * Tech Stack
> * Setup
>   
>   * Prerequisite
>   * Setup Instructions
> * Usage
> 
> Also for the prerequisite provide resources. Make sure to add version of the tech stack too.

Done

**Review by satyam73 — COMMENTED** [review]
Node will also come in Prerequisites
Project overview should have description about the project not the tech stack it's already present in Tech Stack section, try elaborating what tiny site is.

**Review by satyam73 — COMMENTED** [review]
Usage section can be improved in my opinion

**Comment by satyam73** [comment]
If project follows any conventions please also mention the same here

**Comment by satyam73** [comment]
Project overview should have description about the project not the tech stack it's already present in Tech Stack section, try elaborating what tiny site is.

This one is still same

**Pull request merged**
