### PR TITLE
Common imports for types/ interfaces/ utils/ constants/ services

### PR DESCRIPTION
**Pull request by gauravsinhaweb**
- common imports for types in `src/types`
- common imports for constants in `src/utils/constants.ts`

Screenshot 2023-10-28 211117

### CODE REVIEW

**Review by Pratiyushkumar — APPROVED** [review]

**Review by sahsisunny — CHANGES_REQUESTED** [review]
I don't think to separate file for types is necessary if they're uncommon.

**Comment by gauravsinhaweb** [comment]
> I don't think to separate file for types is necessary if they're uncommon.

I got feedback from many devs in my last refactor PR to separate files for types even though they are not reusable and I personally feel it is the correct way to better code structure, maintainability, and enhanced readability.

https://medium.com/mintbean-io/how-i-organize-my-typescript-types-d9ae7f3ac30f

feel free to change your requested changes and approve.

**Comment by gauravsinhaweb** [comment]
In the case of constants, we do the same @sahsisunny

**Comment by sahsisunny** [comment]
> > I don't think to separate file for types is necessary if they're uncommon.
> 
> I got feedback from many devs in my last refactor PR to separate files for types even though they are not reusable and I personally feel it is the correct way to better code structure, maintainability, and enhanced readability.
> 
> https://medium.com/mintbean-io/how-i-organize-my-typescript-types-d9ae7f3ac30f
> 
> feel free to change your requested changes and approve.

Can you mention some devs who suggest you to create separate types for uncommon types?

**Review by sahsisunny — APPROVED** [review]

**Comment by gauravsinhaweb** [comment]
> > > I don't think to separate file for types is necessary if they're uncommon.
> > 
> > 
> > I got feedback from many devs in my last refactor PR to separate files for types even though they are not reusable and I personally feel it is the correct way to better code structure, maintainability, and enhanced readability.
> > https://medium.com/mintbean-io/how-i-organize-my-typescript-types-d9ae7f3ac30f
> > feel free to change your requested changes and approve.
> 
> Can you mention some devs who suggest you to create separate types for uncommon types?

@Pratiyushkumar @satyam73 @yesyash

**Pull request merged**
